/** Düzeltme recipe kimlikleri — motor genişletmesi için sabit sözleşme. */
export const CORRECTION_RECIPE = {
  SAME_ACCOUNT_WRONG_DEBIT: "SAME_ACCOUNT_WRONG_DEBIT",
  WRONG_ACCOUNT_TRANSFER: "WRONG_ACCOUNT_TRANSFER",
  DUPLICATE_REVERSAL: "DUPLICATE_REVERSAL",
  WRONG_SIDE_CORRECTION: "WRONG_SIDE_CORRECTION",
  MISSING_DOCUMENT_COMPLETION: "MISSING_DOCUMENT_COMPLETION",
  ACCOUNT_PLAN_MAPPING: "ACCOUNT_PLAN_MAPPING",
};

/** Şu an uygulanmış recipe'ler (sıra = öncelik). */
export const IMPLEMENTED_CORRECTION_RECIPES = [
  CORRECTION_RECIPE.SAME_ACCOUNT_WRONG_DEBIT,
];

/** Gelecek recipe'ler — kayıtlı ama otomatik fiş üretmez. */
export const PLANNED_CORRECTION_RECIPES = [
  CORRECTION_RECIPE.WRONG_ACCOUNT_TRANSFER,
  CORRECTION_RECIPE.DUPLICATE_REVERSAL,
  CORRECTION_RECIPE.WRONG_SIDE_CORRECTION,
  CORRECTION_RECIPE.MISSING_DOCUMENT_COMPLETION,
  CORRECTION_RECIPE.ACCOUNT_PLAN_MAPPING,
];

export const CORRECTION_DRAFT_STATUS = {
  READY: "READY",
  INVALID: "INVALID",
  BLOCKED: "BLOCKED",
};

export const CORRECTION_EXPORT_MODE = {
  LUCA_STANDARD: "LUCA_STANDARD",
  ANNVERO_FALLBACK: "ANNVERO_FALLBACK",
};
