/**
 * CORE Test Merkezi — hazır senaryolar (Görev 5 global rule seed).
 */

export const CORE_TEST_PRESETS = [
  {
    id: "google-ads",
    label: "GOOGLE ADS PAYMENT",
    description: "GOOGLE ADS PAYMENT",
    amount: "-1250",
    source_type: "bank",
    bank_name: "Vakıfbank",
    expect: {
      entity: "Google",
      account: "770",
      document: "FT",
      cari: "Google",
      manual_review: false,
    },
  },
  {
    id: "meta-ads",
    label: "META ADS PAYMENT",
    description: "META ADS PAYMENT",
    amount: "-980",
    source_type: "bank",
    bank_name: "Garanti",
    expect: {
      entity: "Meta",
      account: "770",
      document: "FT",
      cari: "Meta / Facebook",
      manual_review: false,
    },
  },
  {
    id: "sgk",
    label: "SGK PRIM ODEMESI",
    description: "SGK PRIM ODEMESI 2026/02",
    amount: "-45000",
    source_type: "bank",
    bank_name: "Ziraat",
    expect: {
      entity: "SGK",
      account: "361",
      document: "DK",
      cari: "SGK",
      manual_review: false,
    },
  },
  {
    id: "gib-kdv",
    label: "GIB KDV ODEMESI",
    description: "GIB KDV ODEMESI",
    amount: "-12500",
    source_type: "bank",
    bank_name: "TEB",
    expect: {
      entity: "GİB",
      account: "360",
      document: "DK",
      cari: "GİB",
      manual_review: false,
    },
  },
  {
    id: "turkcell",
    label: "TURKCELL FATURA",
    description: "TURKCELL FATURA ODEMESI",
    amount: "-850",
    source_type: "bank",
    bank_name: "Vakıfbank",
    expect: {
      entity: "Turkcell",
      account: "770",
      document: "FT",
      cari: "Turkcell",
      manual_review: false,
    },
  },
  {
    id: "booking",
    label: "BOOKING.COM TAHSILAT",
    description: "BOOKING.COM TAHSILAT",
    amount: "15000",
    source_type: "bank",
    bank_name: "Garanti",
    expect: {
      entity: "Booking.com",
      account: "120",
      document: "FT",
      cari: "Booking.com",
      manual_review: "optional",
    },
  },
  {
    id: "expedia",
    label: "EXPEDIA TAHSILAT",
    description: "EXPEDIA TAHSILAT",
    amount: "8200",
    source_type: "bank",
    bank_name: "Kuveyt Türk",
    expect: {
      entity: "Expedia",
      account: "120",
      document: "FT",
      cari: "Expedia",
      manual_review: "optional",
    },
  },
];
