/**
 * Mali Yükümlülük Merkezi V1 — domain sabitleri / enum’lar.
 * Mapper’a bağlanmaz; saf motor katmanı.
 */

export const TAX_OBLIGATION_CLASSIFICATION = {
  TAX_OBLIGATION_PAYMENT: "TAX_OBLIGATION_PAYMENT",
  SGK_OBLIGATION_PAYMENT: "SGK_OBLIGATION_PAYMENT",
};

/** Yükümlülük türleri (V1; MTV/Emlak hariç) */
export const OBLIGATION_TYPE = {
  MUHSGK: "MUHSGK",
  KDV1: "KDV1",
  KDV2: "KDV2",
  GECICI_VERGI: "GECICI_VERGI",
  KURUMLAR_VERGISI: "KURUMLAR_VERGISI",
  DAMGA_VERGISI: "DAMGA_VERGISI",
  KONAKLAMA_VERGISI: "KONAKLAMA_VERGISI",
  TURIZM_PAYI: "TURIZM_PAYI",
  SGK: "SGK",
  SGDP: "SGDP",
};

export const DOCUMENT_TYPE = {
  BEYANNAME: "BEYANNAME",
  TAHAKKUK: "TAHAKKUK",
};

export const REVISION_TYPE = {
  NORMAL: "NORMAL",
  DUZELTME: "DUZELTME",
};

export const LINE_TYPE = {
  PRINCIPAL: "PRINCIPAL",
  STAMP_TAX: "STAMP_TAX",
  PENALTY: "PENALTY",
  LATE_FEE: "LATE_FEE",
  LATE_INTEREST: "LATE_INTEREST",
  INCENTIVE: "INCENTIVE",
  OTHER: "OTHER",
};

/** Muhasebe rolü — hesap kodu değil, eşleme anahtarı */
export const ACCOUNTING_ROLE = {
  GELIR_VERGISI_STOPAJ: "GELIR_VERGISI_STOPAJ",
  KIRA_STOPAJ: "KIRA_STOPAJ",
  SERBEST_MESLEK_STOPAJ: "SERBEST_MESLEK_STOPAJ",
  UCRET_STOPAJ: "UCRET_STOPAJ",
  DAMGA_VERGISI: "DAMGA_VERGISI",
  KDV1: "KDV1",
  KDV2_TEVKIFAT: "KDV2_TEVKIFAT",
  SGK_NORMAL: "SGK_NORMAL",
  ISSIZLIK: "ISSIZLIK",
  SGDP: "SGDP",
  GECIKME_ZAMMI: "GECIKME_ZAMMI",
  GECIKME_FAIZI: "GECIKME_FAIZI",
  PISMANLIK_ZAMMI: "PISMANLIK_ZAMMI",
  VERGI_ZIYAI: "VERGI_ZIYAI",
  USULSUZLUK: "USULSUZLUK",
  SGK_INCENTIVE_INCOME: "SGK_INCENTIVE_INCOME",
  OTHER_360: "OTHER_360",
  OTHER_361: "OTHER_361",
  OTHER_EXPENSE: "OTHER_EXPENSE",
};

export const MAPPING_STATUS = {
  MAPPED: "MAPPED",
  MANUAL: "MANUAL",
  PENDING: "PENDING",
};

export const MATCH_STATUS = {
  FULL_MATCH: "FULL_MATCH",
  ACCRUAL_PENDING: "ACCRUAL_PENDING",
  MULTIPLE_CANDIDATES: "MULTIPLE_CANDIDATES",
  LATE_INCENTIVE_SUSPECT: "LATE_INCENTIVE_SUSPECT",
  SUPPORT_VERIFY_PENDING: "SUPPORT_VERIFY_PENDING",
  PARTIAL_PAYMENT: "PARTIAL_PAYMENT",
  OVERPAYMENT: "OVERPAYMENT",
  UNRESOLVED_DIFFERENCE: "UNRESOLVED_DIFFERENCE",
  MANUAL_REVIEW: "MANUAL_REVIEW",
};

export const MATCH_TYPE = {
  AUTO_STRONG: "AUTO_STRONG",
  MANUAL: "MANUAL",
  PARTIAL: "PARTIAL",
  MULTI_ACCRUAL: "MULTI_ACCRUAL",
  MULTI_PAYMENT: "MULTI_PAYMENT",
};

export const PAYMENT_SCENARIO = {
  NORMAL: "NORMAL",
  LATE_INCENTIVE_CANCEL: "LATE_INCENTIVE_CANCEL",
  PAYMENT_SUPPORT: "PAYMENT_SUPPORT",
  PARTIAL: "PARTIAL",
  MAHSUP_OR_REALLOCATION: "MAHSUP_OR_REALLOCATION",
};

export const ACCRUAL_STATUS = {
  OPEN: "OPEN",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  PAID: "PAID",
  SUPERSEDED: "SUPERSEDED",
};

export const SOURCE_PROVIDER = {
  UPLOAD: "upload",
  GOOGLE_DRIVE: "google_drive",
  ONEDRIVE: "onedrive",
};

/** Banka transactionType sabitleri (V1) — mapper wire Paket C */
export const OBLIGATION_TRANSACTION_TYPE = {
  MUHSGK_ODEME: "MUHSGK_ODEME",
  SGK_ODEME: "SGK_ODEME",
  KDV1_ODEME: "KDV1_ODEME",
  KDV2_ODEME: "KDV2_ODEME",
  GECICI_VERGI_ODEME: "GECICI_VERGI_ODEME",
  KURUMLAR_VERGISI_ODEME: "KURUMLAR_VERGISI_ODEME",
  DAMGA_VERGISI_ODEME: "DAMGA_VERGISI_ODEME",
  KONAKLAMA_VERGISI_ODEME: "KONAKLAMA_VERGISI_ODEME",
  TURIZM_PAYI_ODEME: "TURIZM_PAYI_ODEME",
};

export const PARSER_VERSION = "tax-obligation-v1";

/** UI / mutabakat durum etiketleri */
export const MATCH_STATUS_LABEL = {
  [MATCH_STATUS.FULL_MATCH]: "Tam eşleşti",
  [MATCH_STATUS.ACCRUAL_PENDING]: "Tahakkuk bekleniyor",
  [MATCH_STATUS.MULTIPLE_CANDIDATES]: "Birden fazla tahakkuk adayı",
  [MATCH_STATUS.LATE_INCENTIVE_SUSPECT]: "Geç ödeme / teşvik iptali şüphesi",
  [MATCH_STATUS.SUPPORT_VERIFY_PENDING]: "Destek farkı doğrulama bekliyor",
  [MATCH_STATUS.PARTIAL_PAYMENT]: "Kısmi ödeme",
  [MATCH_STATUS.OVERPAYMENT]: "Fazla ödeme",
  [MATCH_STATUS.UNRESOLVED_DIFFERENCE]: "Çözülmemiş tutar farkı",
  [MATCH_STATUS.MANUAL_REVIEW]: "Manuel inceleme",
};
